// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb7ssDk4VeMDgJW80q285kvDZL_iEkYd0',
    appId: '1:813634226707:web:d17669a0fed1046645cde6',
    messagingSenderId: '813634226707',
    projectId: 'fir-add-fc11c',
    authDomain: 'fir-add-fc11c.firebaseapp.com',
    storageBucket: 'fir-add-fc11c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzTVpjxZ8437DSEDRqi16aVkbV88hxIM',
    appId: '1:813634226707:android:703ae06508fc4f8f45cde6',
    messagingSenderId: '813634226707',
    projectId: 'fir-add-fc11c',
    storageBucket: 'fir-add-fc11c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnd5ez1McEs7ecBES1wiZpYhSW41NxoDA',
    appId: '1:813634226707:ios:bb928a06bee5134345cde6',
    messagingSenderId: '813634226707',
    projectId: 'fir-add-fc11c',
    storageBucket: 'fir-add-fc11c.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnd5ez1McEs7ecBES1wiZpYhSW41NxoDA',
    appId: '1:813634226707:ios:1285839aad73b44945cde6',
    messagingSenderId: '813634226707',
    projectId: 'fir-add-fc11c',
    storageBucket: 'fir-add-fc11c.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
